name: Gilles Bertaux - Digital Planner
markdown: redcarpet
pygments: true
timezone: Europe/Paris
permalink: /:title.html
baseurl: /blog-jekyll/
url: http://gillesbertaux.github.io
paginate: 5
paginate_path: 'page:num'
destination: _site/